[workspace]
authors = ["Juan P. Fonseca-Zamora <69847296+juanfonsecaLS1@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "01_DfT_Analysis"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
bokeh = ">=3.7.3,<4"
momepy = ">=0.10.0,<0.11"
neatnet = ">=0.1.2,<0.2"
numba = ">=0.61.2,<0.62"
osmnx = ">=2.0.6,<3"
shapely = ">=2.1.1,<3"
pip = ">=25.2,<26"
mapclassify = ">=2.10.0,<3"
geopandas = ">=1.1.1,<2"
scikit-learn = ">=1.7.1,<2"
clustergram = ">=0.8.1,<0.9"
ruff = ">=0.12.10,<0.13"
conda-build = ">=25.7.0,<26"

[pypi-dependencies]
geoplanar = ">=0.4.0, <0.5"
